name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        ruby: [2.3, 2.4, 2.5, 2.6, 2.7] # TODO: jruby
        platform: [ubuntu-latest, macos-latest] # TODO: windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Test
        run: rake test
